---
- name: First Playbook für alle Hosts
  hosts: all
  become: yes

  tasks:

    - name: "=== DEBUG === Zeige Distribution an"
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_os_family }}"

- name: Debian/Ubuntu Setup
  hosts: ubuntu_ssh
  become: yes

  tasks:
    - name: Update Paketlisten (Debian/Ubuntu)
      apt:
        update_cache: yes

    - name: Installiere Tools auf Debian/Ubuntu
      apt:
        name:
          - htop
          - curl
          - vim
          - git
          - ufw
        state: present

- name: Rocky/RHEL Setup
  hosts: rocky_ssh
  become: yes

  tasks:
    - name: Repositories updaten (Rocky/RHEL)
      dnf:
        update_cache: yes

    - name: Installiere EPEL-Repository (Rocky/RHEL)
      dnf:
        name: epel-release
        state: present

    - name: Entferne curl-minimal falls vorhanden (Rocky/RHEL)
      dnf:
        name: curl-minimal
        state: absent

    - name: Installiere Tools auf Rocky/RHEL
      dnf:
        name:
          - htop
          - curl
          - vim
          - git
          - firewalld
        state: present

