FROM rockylinux:9

# Installiere SSH und benötigte Tools
RUN dnf install -y openssh-server passwd iproute && \
    mkdir /var/run/sshd && \
    ssh-keygen -A

# Erstelle das .ssh-Verzeichnis und setze die Berechtigungen
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

# Kopiere den PUBLIC Key in authorized_keys und setze die richtigen Berechtigungen
COPY rocky-ssh-key.pub /root/.ssh/authorized_keys

RUN chmod 600 /root/.ssh/authorized_keys && \
    chown -R root:root /root/.ssh

# SSHD-Konfiguration anpassen
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config

# Port freigeben
EXPOSE 22

# SSH Daemon starten
CMD ["/usr/sbin/sshd", "-D"]

